###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    redis:
        image: 'redis:alpine'

    mysql:
        image: 'mysql:8.0'
        container_name: mysqldb-container
        working_dir: /application
        volumes:
            - ./phpdocker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mysqldb
            - MYSQL_USER=mysqluser
            - MYSQL_PASSWORD=mysqlpass
        ports:
            - '5002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '5000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'

  # Link to phpmyadmin
  # http://localhost:5036/
    phpMyAdmin:
        depends_on:
          - mysql
        image: phpmyadmin
        restart: always
        ports:
          - 5036:80
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - PMA_HOST=mysql
          - PMA_PORT=3306
          - PMA_ARBITRARY=1
          - PMA_USER=mysqluser
          - PMA_PASSWORD=mysqlpass
